/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.client.view;

import edu.sebsx.app.linkedlist.singly.SinglyLinkedList;
import edu.sebsx.model.iterator.Iterator;
import edu.upb.client.model.ClientModel;
import edu.upb.model.Passenger;
import javax.swing.JOptionPane;

/**
 * Ventana que muestra el orden de abordaje de los pasajeros para un tren específico.
 *
 * @author Sebastian Alberto Pinto Torres
 * @version 1.0
 */
public class BoardingView extends javax.swing.JFrame {
    
    private transient ClientModel model;

    /**
     * Creates new form BoardingView
     */
    public BoardingView() {
        initComponents();
    }
    
    public BoardingView(ClientModel model) {
        this.model = model;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void loadBoardingOrder(String trainId) {
        SinglyLinkedList<Passenger> order = model.getBoardingOrder(trainId);
        if (order.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay pasajeros para abordar.");
            return;
        }
        StringBuilder sb = new StringBuilder();
        sb.append("=== ORDEN DE ABORDAJE ===\n");
        Iterator<Passenger> it = order.iterator();
        int pos = 1;
        while (it.hasNext()) {
            Passenger p = it.next();
            sb.append(pos++).append(". ").append(p.getName()).append("\n");
        }
        txtOrder.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrder = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitor de abordaje - UPB");
        setResizable(false);

        lbl.setText("Orden de abordaje");

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtOrder.setEditable(false);
        txtOrder.setColumns(30);
        txtOrder.setRows(10);
        jScrollPane1.setViewportView(txtOrder);

        btnClose.setText("Cerrar");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextArea txtOrder;
    // End of variables declaration//GEN-END:variables
}