/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.client.view;

import edu.upb.client.model.ClientModel;
import java.util.function.Consumer;

/**
 * Ventana de inicio de sesión del sistema.
 *
 * @author Sebastian Alberto Pinto Torres
 * @version 1.0
 */
public class LoginView extends javax.swing.JFrame {
    
    private transient Consumer<String> onLoginSuccess;
    private transient java.util.function.BiConsumer<edu.upb.common.LoginDTO, Consumer<Boolean>> loginHandler;
    private transient java.util.function.BiConsumer<Object[], Consumer<Boolean>> registerHandler;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }
    
    public LoginView(ClientModel model) {
        initComponents();
        
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu menu = new javax.swing.JMenu("Opciones");
        javax.swing.JMenuItem itemRegister = new javax.swing.JMenuItem("Registrar Usuario");
        itemRegister.addActionListener(e -> registerUserFlow());
        menu.add(itemRegister);
        menuBar.add(menu);
        setJMenuBar(menuBar);
        
        setLocationRelativeTo(null);
    }
    
    private void registerUserFlow() {
        javax.swing.JTextField txtId = new javax.swing.JTextField();
        javax.swing.JTextField txtName = new javax.swing.JTextField();
        javax.swing.JTextField txtLastName = new javax.swing.JTextField();
        javax.swing.JTextField txtUser = new javax.swing.JTextField();
        javax.swing.JPasswordField txtPass = new javax.swing.JPasswordField();
        javax.swing.JComboBox<String> cmbRole = new javax.swing.JComboBox<>(new String[]{"ADMIN", "OPERATOR", "STANDARD_USER"});
        
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1));
        panel.add(new javax.swing.JLabel("ID:"));
        panel.add(txtId);
        panel.add(new javax.swing.JLabel("Nombre:"));
        panel.add(txtName);
        panel.add(new javax.swing.JLabel("Apellido:"));
        panel.add(txtLastName);
        panel.add(new javax.swing.JLabel("Usuario:"));
        panel.add(txtUser);
        panel.add(new javax.swing.JLabel("Contraseña:"));
        panel.add(txtPass);
        panel.add(new javax.swing.JLabel("Rol:"));
        panel.add(cmbRole);
        
        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Registrar Usuario", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (result == javax.swing.JOptionPane.OK_OPTION) {
            String id = txtId.getText().trim();
            String name = txtName.getText().trim();
            String lastName = txtLastName.getText().trim();
            String user = txtUser.getText().trim();
            String pass = new String(txtPass.getPassword());
            String role = (String) cmbRole.getSelectedItem();
            if (id.isEmpty() || user.isEmpty() || pass.isEmpty() || name.isEmpty() || lastName.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
                return;
            }
            if (registerHandler != null) {
                registerHandler.accept(new Object[]{id, user, pass, role, name, lastName}, success -> {
                    if (success) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.");
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar (el usuario ya existe o error RMI).");
                    }
                });
            }
        }
    }
    
    public void setHandlers(java.util.function.BiConsumer<edu.upb.common.LoginDTO, Consumer<Boolean>> loginHandler, 
                          java.util.function.BiConsumer<Object[], Consumer<Boolean>> registerHandler) {
        this.loginHandler = loginHandler;
        this.registerHandler = registerHandler;
    }
    
    public void setOnLoginSuccess(Consumer<String> handler) {
        this.onLoginSuccess = handler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Trenes UPB");

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jTextField1.setName("txtUsername"); // NOI18N

        jPasswordField1.setName("txtPassword"); // NOI18N

        jButton1.setText("Iniciar sesión");
        jButton1.setName("btnLogin"); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel3.setName("lblMessage"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = jTextField1.getText().trim();
        String password = new String(jPasswordField1.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            jLabel3.setText("Usuario y contraseña obligatorios.");
            return;
        }

        try {
            if (loginHandler != null) {
                edu.upb.common.LoginDTO dto = new edu.upb.common.LoginDTO();
                dto.setUsername(username);
                dto.setPassword(password);
                loginHandler.accept(dto, valid -> {
                    if (valid) {
                        jLabel3.setText("");
                        if (onLoginSuccess != null) onLoginSuccess.accept(username);
                    } else {
                        jLabel3.setText("Credenciales inválidas.");
                    }
                });
            }
        } catch (Exception _) {
            jLabel3.setText("Error de conexión.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
