/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.client.view;

import edu.upb.common.SaleDTO;
import edu.upb.model.Ticket;
import java.util.function.Consumer;
import javax.swing.JOptionPane;

/**
 * Ventana de compra de boletos que simula una máquina de estación.
 *
 * @author Sebastian Alberto Pinto Torres
 * @version 1.0
 */
public class PurchaseView extends javax.swing.JFrame {
    
    private transient Consumer<SaleDTO> purchaseHandler;

    /**
     * Creates new form PurchaseView
     */
    public PurchaseView() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setStationNames(String[] stations) {
        cmbOrigin.removeAllItems();
        cmbDest.removeAllItems();
        for (String s : stations) {
            cmbOrigin.addItem(s);
            cmbDest.addItem(s);
        }
    }
    
    public void setPurchaseHandler(Consumer<SaleDTO> handler) {
        this.purchaseHandler = handler;
    }
    
    public void showTicket(Ticket ticket) {
        StringBuilder sb = new StringBuilder();
        sb.append("=== BOLETO EMITIDO ===\n");
        sb.append("ID: ").append(ticket.getRegistrationId()).append("\n");
        sb.append("Pasajero: ").append(ticket.getPassengerName()).append("\n");
        sb.append("Categoría: ").append(ticket.getCategory()).append("\n");
        sb.append("Asiento: ").append(ticket.getSeatNumber()).append("\n");
        sb.append("Valor: $").append(ticket.getFareValue()).append("\n");
        txtResult.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbOrigin = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbDest = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBaggage = new javax.swing.JTextField();
        btnPurchase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compra de Boletos - Trenes UPB");
        setResizable(false);

        jLabel1.setText("Origen:");

        cmbOrigin.setName("cmbOrigin"); // NOI18N

        jLabel2.setText("Destino:");

        cmbDest.setName("cmbDest"); // NOI18N

        jLabel3.setText("Categoría:");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premium", "Ejecutivo", "Estándar" }));
        cmbCategory.setToolTipText("");
        cmbCategory.setName("cmbCategory"); // NOI18N
        cmbCategory.setOpaque(true);

        jLabel4.setText("Nombre:");

        txtName.setName("txtName"); // NOI18N

        jLabel5.setText("Peso equipaje (kg):");

        txtBaggage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtBaggage.setToolTipText("");
        txtBaggage.setName("txtBaggage"); // NOI18N

        btnPurchase.setText("Comprar boleto");
        btnPurchase.setName("btnPurchase"); // NOI18N
        btnPurchase.addActionListener(this::btnPurchaseActionPerformed);

        txtResult.setColumns(20);
        txtResult.setRows(5);
        txtResult.setName("txtResult"); // NOI18N
        jScrollPane1.setViewportView(txtResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBaggage, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPurchase)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBaggage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPurchase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        String origin = (String) cmbOrigin.getSelectedItem();
        String dest = (String) cmbDest.getSelectedItem();
        String category = (String) cmbCategory.getSelectedItem();
        String name = txtName.getText().trim();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del pasajero.");
            return;
        }
        if (origin == null || dest == null || origin.equals(dest)) {
            JOptionPane.showMessageDialog(this, "Origen y destino deben ser diferentes.");
            return;
        }

        double baggage = 0;
        try {
            baggage = Double.parseDouble(txtBaggage.getText().trim());
        } catch (NumberFormatException _) {
            JOptionPane.showMessageDialog(this, "Peso de equipaje inválido.");
            return;
        }

        SaleDTO dto = new SaleDTO();
        dto.setOrigin(origin);
        dto.setDestination(dest);
        dto.setCategory(category);
        dto.setPassengerName(name);
        dto.setBaggageWeight(baggage);
        dto.setTrainId("TEMP");

        if (purchaseHandler != null) purchaseHandler.accept(dto);
    }//GEN-LAST:event_btnPurchaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchase;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbDest;
    private javax.swing.JComboBox<String> cmbOrigin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBaggage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}