/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.client.view;

import edu.upb.common.SaleDTO;
import edu.upb.model.Ticket;
import java.util.function.Consumer;
import javax.swing.JOptionPane;

/**
 * Ventana de compra de boletos que simula una máquina de estación.
 *
 * @author Sebastian Alberto Pinto Torres
 * @version 1.0
 */
public class PurchaseView extends javax.swing.JFrame {

        private transient Consumer<SaleDTO> purchaseHandler;
        private transient edu.upb.client.model.ClientModel model;

        /**
         * Creates new form PurchaseView
         */
        public PurchaseView(edu.upb.client.model.ClientModel model) {
                this.model = model;
                initComponents();
                setLocationRelativeTo(null);
                cmbOrigin.addActionListener(e -> updateRouteInfo());
                cmbDest.addActionListener(e -> updateRouteInfo());
        }

        /**
         * Establece los nombres de las estaciones en los combos de origen y destino.
         * 
         * @param stations Arreglo de nombres de estaciones.
         */
        public void setStationNames(String[] stations) {
                cmbOrigin.removeAllItems();
                cmbDest.removeAllItems();
                for (String s : stations) {
                        cmbOrigin.addItem(s);
                        cmbDest.addItem(s);
                }
                this.pack();
                this.setLocationRelativeTo(null);
        }

        /**
         * Establece el manejador para la acción de compra.
         * 
         * @param handler Consumidor que procesa el SaleDTO.
         */
        public void setPurchaseHandler(Consumer<SaleDTO> handler) {
                this.purchaseHandler = handler;
        }

        /**
         * Muestra la información del tiquete emitido en el área de texto.
         * 
         * @param ticket El tiquete generado.
         */
        public void showTicket(Ticket ticket) {
                StringBuilder sb = new StringBuilder();
                sb.append("=== BOLETO EMITIDO ===\n");
                sb.append("ID: ").append(ticket.getRegistrationId()).append("\n");
                sb.append("Pasajero: ").append(ticket.getPassengerName()).append("\n");
                sb.append("Categoría: ").append(ticket.getCategory()).append("\n");
                sb.append("Asiento: ").append(ticket.getSeatNumber()).append("\n");
                sb.append("Valor: $").append(ticket.getFareValue()).append("\n");
                txtResult.setText(sb.toString());
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                cmbOrigin = new javax.swing.JComboBox<>();
                jLabel2 = new javax.swing.JLabel();
                cmbDest = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                cmbCategory = new javax.swing.JComboBox<>();
                jLabel4 = new javax.swing.JLabel();
                txtName = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtBaggage = new javax.swing.JTextField();
                btnPurchase = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Compra de Boletos - Trenes UPB");

                jLabel1.setText("Origen:");
                jLabel2.setText("Destino:");
                jLabel3.setText("Categoría:");
                cmbCategory
                                .setModel(new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Premium", "Ejecutivo", "Estándar" }));

                jLabel4.setText("Nombre:");
                jLabelLastName = new javax.swing.JLabel("Apellido:");
                txtLastName = new javax.swing.JTextField();

                jLabelId = new javax.swing.JLabel("ID:");
                txtIdNumber = new javax.swing.JTextField();
                jLabelIdType = new javax.swing.JLabel("Tipo ID:");
                cmbIdType = new javax.swing.JComboBox<>(new String[] { "CC", "TI", "PAS", "CE" });

                jLabelAddress = new javax.swing.JLabel("Dirección:");
                txtAddress = new javax.swing.JTextField();
                jLabelPhone = new javax.swing.JLabel("Teléfono:");
                txtPhone = new javax.swing.JTextField();

                jLabelContactName = new javax.swing.JLabel("Contacto:");
                txtContactName = new javax.swing.JTextField();
                jLabelContactLastName = new javax.swing.JLabel("Apellido C.:");
                txtContactLastName = new javax.swing.JTextField();
                jLabelContactPhone = new javax.swing.JLabel("Tel. C.:");
                txtContactPhone = new javax.swing.JTextField();

                jLabel5.setText("Peso equipaje (kg):");
                lblRouteInfo = new javax.swing.JLabel("Seleccione origen y destino para ver la ruta más corta.");

                btnPurchase.setText("Comprar boleto");
                btnPurchase.addActionListener(this::btnPurchaseActionPerformed);

                txtResult = new javax.swing.JTextArea();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtResult.setColumns(20);
                txtResult.setRows(5);
                jScrollPane1.setViewportView(txtResult);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane1)
                                                                                .addComponent(lblRouteInfo)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel1)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(cmbOrigin,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(cmbDest,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(jLabelId)
                                                                                                                                                .addComponent(jLabelAddress)
                                                                                                                                                .addComponent(jLabelContactName))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(txtName,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                110,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(txtIdNumber)
                                                                                                                                                .addComponent(txtAddress)
                                                                                                                                                .addComponent(txtContactName))
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabelLastName)
                                                                                                                                                .addComponent(jLabelIdType)
                                                                                                                                                .addComponent(jLabelPhone)
                                                                                                                                                .addComponent(jLabelContactLastName))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(txtLastName,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                110,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(cmbIdType,
                                                                                                                                                                0,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(txtPhone)
                                                                                                                                                .addComponent(txtContactLastName))
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(cmbCategory,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabelContactPhone)
                                                                                                                                                .addComponent(txtContactPhone,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                .addGap(0, 15, Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel5)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txtBaggage,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                50,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnPurchase,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                150,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(25, 25, 25)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(cmbOrigin,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(cmbDest,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(txtName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabelLastName)
                                                                                .addComponent(txtLastName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelId)
                                                                                .addComponent(txtIdNumber,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabelIdType)
                                                                                .addComponent(cmbIdType,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(cmbCategory,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelAddress)
                                                                                .addComponent(txtAddress,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabelPhone)
                                                                                .addComponent(txtPhone,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelContactName)
                                                                                .addComponent(txtContactName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabelContactLastName)
                                                                                .addComponent(txtContactLastName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabelContactPhone)
                                                                                .addComponent(txtContactPhone,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(txtBaggage,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnPurchase))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblRouteInfo)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                133,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(25, 25, 25)));

                pack();
        }

        private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {
                String origin = (String) cmbOrigin.getSelectedItem();
                String dest = (String) cmbDest.getSelectedItem();
                String category = (String) cmbCategory.getSelectedItem();
                String name = txtName.getText().trim();
                String lastName = txtLastName.getText().trim();
                String idNumber = txtIdNumber.getText().trim();
                String idType = (String) cmbIdType.getSelectedItem();
                String address = txtAddress.getText().trim();
                String phone = txtPhone.getText().trim();
                String contactName = txtContactName.getText().trim();
                String contactLastName = txtContactLastName.getText().trim();
                String contactPhone = txtContactPhone.getText().trim();

                if (name.isEmpty() || lastName.isEmpty() || idNumber.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Nombre, Apellido e ID son obligatorios.");
                        return;
                }
                if (origin == null || dest == null || origin.equals(dest)) {
                        JOptionPane.showMessageDialog(this, "Origen y destino deben ser diferentes.");
                        return;
                }

                if (model != null) {
                        double distance = model.getShortestDistance(origin, dest);
                        if (distance <= 0) {
                                JOptionPane.showMessageDialog(this, "No hay ruta disponible.");
                                return;
                        }
                }

                double baggage = 0;
                try {
                        String bText = txtBaggage.getText().trim();
                        baggage = bText.isEmpty() ? 0 : Double.parseDouble(bText);
                } catch (NumberFormatException _) {
                        JOptionPane.showMessageDialog(this, "Peso de equipaje inválido (use números).");
                        return;
                }

                SaleDTO dto = new SaleDTO();
                dto.setOrigin(origin);
                dto.setDestination(dest);
                dto.setCategory(category);
                dto.setPassengerName(name);
                dto.setPassengerLastName(lastName);
                dto.setPassengerId(idNumber);
                dto.setIdType(idType);
                dto.setAddress(address);
                dto.setPhoneNumbers(phone);
                dto.setContactPersonName(contactName);
                dto.setContactPersonLastName(contactLastName);
                dto.setContactPersonPhone(contactPhone);
                dto.setBaggageWeight(baggage);
                dto.setTrainId("AUTO");

                if (purchaseHandler != null)
                        purchaseHandler.accept(dto);
        }

        private void updateRouteInfo() {
                String origin = (String) cmbOrigin.getSelectedItem();
                String dest = (String) cmbDest.getSelectedItem();
                if (origin == null || dest == null || origin.equals(dest)) {
                        lblRouteInfo.setText("Origen y destino deben ser diferentes.");
                        return;
                }
                if (model != null) {
                        double distance = model.getShortestDistance(origin, dest);
                        if (distance > 0) {
                                double basePrice = distance * 100;
                                lblRouteInfo.setText(
                                                String.format("Distancia: %.2f km | Precio base: $%.2f", distance, basePrice));
                        } else {
                                lblRouteInfo.setText("No hay ruta disponible entre estas estaciones.");
                        }
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnPurchase;
        private javax.swing.JComboBox<String> cmbCategory;
        private javax.swing.JComboBox<String> cmbDest;
        private javax.swing.JComboBox<String> cmbOrigin;
        private javax.swing.JComboBox<String> cmbIdType;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabelLastName;
        private javax.swing.JLabel jLabelId;
        private javax.swing.JLabel jLabelIdType;
        private javax.swing.JLabel jLabelAddress;
        private javax.swing.JLabel jLabelPhone;
        private javax.swing.JLabel jLabelContactName;
        private javax.swing.JLabel jLabelContactLastName;
        private javax.swing.JLabel jLabelContactPhone;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField txtBaggage;
        private javax.swing.JTextField txtName;
        private javax.swing.JTextField txtLastName;
        private javax.swing.JTextField txtIdNumber;
        private javax.swing.JTextField txtAddress;
        private javax.swing.JTextField txtPhone;
        private javax.swing.JTextField txtContactName;
        private javax.swing.JTextField txtContactLastName;
        private javax.swing.JTextField txtContactPhone;
        private javax.swing.JLabel lblRouteInfo;
        private javax.swing.JTextArea txtResult;
        // End of variables declaration//GEN-END:variables
}