/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.client.view;

import edu.upb.client.model.ClientModel;
import edu.upb.common.SaleDTO;
import edu.upb.model.Ticket;
import java.util.function.Consumer;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PurchaseView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PurchaseView.class.getName());
    
    private ClientModel model;
    private Consumer<SaleDTO> purchaseHandler;

    /**
     * Creates new form PurchaseView
     */
    public PurchaseView(ClientModel model) {
        this.model = model;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setStationNames(String[] stations) {
        for (String s : stations) {
            cmbOrigin.addItem(s);
            cmbDest.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbOrigin = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbDest = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBaggage = new javax.swing.JTextField();
        btnPurchase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compra de Boletos - Trenes UPB");

        jLabel1.setText("Origen:");

        cmbOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrigin.setName("cmbOrigin"); // NOI18N
        cmbOrigin.addActionListener(this::cmbOriginActionPerformed);

        jLabel2.setText("Destino:");

        cmbDest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDest.setName("cmbDest"); // NOI18N
        cmbDest.addActionListener(this::cmbDestActionPerformed);

        jLabel3.setText("Categoría:");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premium", "Ejecutivo", "Estándar" }));
        cmbCategory.setToolTipText("");
        cmbCategory.setName("cmbCategory"); // NOI18N
        cmbCategory.setOpaque(true);
        cmbCategory.addActionListener(this::cmbCategoryActionPerformed);

        jLabel4.setText("Nombre:");

        txtName.setForeground(new java.awt.Color(100, 100, 100));
        txtName.setText("Ej. Pepito");
        txtName.setName("txtName"); // NOI18N
        txtName.addActionListener(this::txtNameActionPerformed);

        jLabel5.setText("Peso equipaje (kg):");

        txtBaggage.setText("0");
        txtBaggage.setToolTipText("");
        txtBaggage.setName("txtBaggage"); // NOI18N

        btnPurchase.setText("Comprar boleto");
        btnPurchase.setName("btnPurchase"); // NOI18N
        btnPurchase.addActionListener(this::btnPurchaseActionPerformed);

        txtResult.setColumns(20);
        txtResult.setRows(5);
        txtResult.setName("txtResult"); // NOI18N
        jScrollPane1.setViewportView(txtResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbCategory, 0, 1, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBaggage, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPurchase)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBaggage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOriginActionPerformed

    private void cmbDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDestActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed

    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        String origin = (String) cmbOrigin.getSelectedItem();
        String dest = (String) cmbDest.getSelectedItem();
        String category = (String) cmbCategory.getSelectedItem();
        String name = txtName.getText().trim();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del pasajero.");
            return;
        }
        if (origin == null || dest == null || origin.equals(dest)) {
            JOptionPane.showMessageDialog(this, "Origen y destino deben ser diferentes.");
            return;
        }

        double baggage = 0;
        try {
            baggage = Double.parseDouble(txtBaggage.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Peso de equipaje inválido.");
            return;
        }

        SaleDTO dto = new SaleDTO();
        dto.setOrigin(origin);
        dto.setDestination(dest);
        dto.setCategory(category);
        dto.setPassengerName(name);
        dto.setBaggageWeight(baggage);
        dto.setTrainId("TEMP");

        if (purchaseHandler != null) {
            purchaseHandler.accept(dto);
        }
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    
    public void showTicket(Ticket ticket) {
        StringBuilder sb = new StringBuilder();
        sb.append("=== BOLETO EMITIDO ===\n");
        sb.append("ID: ").append(ticket.getRegistrationId()).append("\n");
        sb.append("Pasajero: ").append(ticket.getPassengerName()).append("\n");
        sb.append("Categoría: ").append(ticket.getCategory()).append("\n");
        sb.append("Asiento: ").append(ticket.getSeatNumber()).append("\n");
        sb.append("Valor: $").append(ticket.getFareValue()).append("\n");
        txtResult.setText(sb.toString());
    }

    public void setPurchaseHandler(Consumer<SaleDTO> handler) {
        this.purchaseHandler = handler;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PurchaseView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchase;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbDest;
    private javax.swing.JComboBox<String> cmbOrigin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBaggage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
