/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.client.view;

import edu.sebsx.model.iterator.Iterator;
import edu.sebsx.model.list.List;
import edu.upb.client.model.ClientModel;
import edu.upb.model.Route;
import edu.upb.model.Station;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import edu.upb.common.observer.Observer;

/**
 * Ventana para la gestión de rutas y horarios del sistema ferroviario.
 *
 * @author Sebastian Alberto Pinto Torres
 * @version 1.0
 */
public class RouteView extends javax.swing.JFrame implements Observer {

    private transient ClientModel model;
    private Route selectedRoute = null;

    /**
     * Creates new form RouteView
     */
    public RouteView() {
        initComponents();
    }

    public RouteView(ClientModel model) {
        this.model = model;
        this.model.attach(this);
        initComponents();
        setLocationRelativeTo(null);
        loadRoutesToTable();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                model.detach(RouteView.this);
            }
        });
    }

    public void setStationNames(String[] stations) {
        cmbOrigin.removeAllItems();
        cmbDest.removeAllItems();
        for (String s : stations) {
            cmbOrigin.addItem(s);
            cmbDest.addItem(s);
        }
        this.pack();
        this.setLocationRelativeTo(null);
    }

    @Override
    public void update(String event) {
        if (event.startsWith("ROUTE_")) {
            loadRoutesToTable();
        }
    }

    private void loadRoutesToTable() {
        try {
            List<Route> routes = model.getAllRoutes();
            DefaultTableModel tableModel = (DefaultTableModel) tblRoutes.getModel();
            tableModel.setRowCount(0);
            Iterator<Route> it = routes.iterator();
            while (it.hasNext()) {
                Route r = it.next();
                String origin = "";
                String dest = "";
                Iterator<Station> stIt = r.getStations().iterator();
                if (stIt.hasNext())
                    origin = stIt.next().getName();
                if (stIt.hasNext())
                    dest = stIt.next().getName();
                tableModel.addRow(new Object[] {
                        r.getId(), origin, dest, r.getDistance(),
                        r.getDepartureTime(), r.getArrivalTime()
                });
            }
        } catch (Exception e) {
            lblMessage.setText("Error al cargar rutas: " + e.getMessage());
        }
    }

    private void clearForm() {
        txtId.setText("");
        cmbOrigin.setSelectedIndex(0);
        cmbDest.setSelectedIndex(0);
        txtDistance.setText("");
        txtDeparture.setText("");
        txtArrival.setText("");
        selectedRoute = null;
        tblRoutes.clearSelection();
    }

    private boolean validateForm() {
        if (txtId.getText().trim().isEmpty()) {
            lblMessage.setText("El ID es obligatorio.");
            return false;
        }
        try {
            Double.parseDouble(txtDistance.getText().trim());
        } catch (NumberFormatException _) {
            lblMessage.setText("La distancia debe ser un número.");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblOrigin = new javax.swing.JLabel();
        cmbOrigin = new javax.swing.JComboBox<>();
        lblDest = new javax.swing.JLabel();
        cmbDest = new javax.swing.JComboBox<>();
        lblDistance = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        tblRoutes = new javax.swing.JTable();
        lblMessage = new javax.swing.JLabel();
        lblDeparture = new javax.swing.JLabel();
        lblArrival = new javax.swing.JLabel();
        txtDeparture = new javax.swing.JTextField();
        txtArrival = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de rutas - UPB");

        lblId.setText("ID Ruta:");

        lblOrigin.setText("Origen:");

        lblDest.setText("Destino:");

        lblDistance.setText("Distancia (km):");

        btnAdd.setText("Agregar ruta");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnRefresh.setText("Refrescar");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        tblRoutes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "ID", "Origen", "Destino", "Distancia (km)", "Salida", "Llegada"
                }));
        scrollPane.setViewportView(tblRoutes);

        lblDeparture.setText("Salida (HH:MM):");

        lblArrival.setText("Llegada (HH:MM):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addComponent(btnAdd)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(btnUpdate)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(btnDelete)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(btnRefresh))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(lblDeparture)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txtDeparture,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        81,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(lblId)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addComponent(txtId,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        103,
                                                                                                        Short.MAX_VALUE))
                                                                                .addGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        lblDistance)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(
                                                                                                        txtDistance,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        86,
                                                                                                        Short.MAX_VALUE))))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(lblDest)
                                                                                        .addComponent(lblOrigin,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addComponent(cmbOrigin, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(cmbDest,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                135,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(lblArrival)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txtArrival,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        83,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addContainerGap(20, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblId)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOrigin)
                                        .addComponent(cmbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDest)
                                        .addComponent(cmbDest, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDistance)
                                        .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDeparture)
                                        .addComponent(lblArrival)
                                        .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDelete)
                                        .addComponent(btnRefresh))
                                .addGap(26, 26, 26)
                                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 166,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
        if (!validateForm() || selectedRoute == null) {
            lblMessage.setText("Seleccione una ruta para actualizar.");
            return;
        }
        selectedRoute.setDistance(Double.parseDouble(txtDistance.getText().trim()));
        selectedRoute.setDepartureTime(txtDeparture.getText().trim());
        selectedRoute.setArrivalTime(txtArrival.getText().trim());
        try {
            if (model.updateRoute(selectedRoute)) {
                clearForm();
                lblMessage.setText("Ruta actualizada.");
            } else {
                lblMessage.setText("Error al actualizar.");
            }
        } catch (Exception e) {
            lblMessage.setText("Error: " + e.getMessage());
        }
    }// GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedRoute == null) {
            lblMessage.setText("Seleccione una ruta para eliminar.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar la ruta " + selectedRoute.getId() + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION)
            return;
        try {
            if (model.deleteRoute(selectedRoute.getId())) {
                clearForm();
                lblMessage.setText("Ruta eliminada.");
            } else {
                lblMessage.setText("Error al eliminar.");
            }
        } catch (Exception e) {
            lblMessage.setText("Error: " + e.getMessage());
        }
    }// GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        loadRoutesToTable();
        clearForm();
        lblMessage.setText("Lista actualizada.");
    }// GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        if (!validateForm())
            return;
        Route route = new Route(txtId.getText().trim());
        route.addStation(new Station((String) cmbOrigin.getSelectedItem(), (String) cmbOrigin.getSelectedItem()));
        route.addStation(new Station((String) cmbDest.getSelectedItem(), (String) cmbDest.getSelectedItem()));
        route.setDistance(Double.parseDouble(txtDistance.getText().trim()));
        route.setDepartureTime(txtDeparture.getText().trim());
        route.setArrivalTime(txtArrival.getText().trim());
        try {
            if (model.addRoute(route)) {
                clearForm();
                lblMessage.setText("Ruta agregada.");
            } else {
                lblMessage.setText("Error al agregar ruta.");
            }
        } catch (Exception e) {
            lblMessage.setText("Error: " + e.getMessage());
        }
    }// GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDest;
    private javax.swing.JComboBox<String> cmbOrigin;
    private javax.swing.JLabel lblArrival;
    private javax.swing.JLabel lblDeparture;
    private javax.swing.JLabel lblDest;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOrigin;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblRoutes;
    private javax.swing.JTextField txtArrival;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}